kind: pipeline
name: default

steps:
- name: build
  image: docker
  commands:
  - docker build -t ${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA} ./src
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: publish
  image: plugins/gcr
  settings:
    repo: kapb14/digitaloctober-example
    tags: latest
    json_key:
      from_secret: google_credentials

#- name: deploy
#  image: quay.io/honestbee/drone-kubernetes
#  kubernetes_server: https://kubernetes.company.org
#  kubernetes_token: CXHVLJSDKJFS...
#  namespace: default
#  deployment: digitaloctober-example
#  repo: myorg/myrepo
#  container: my-container
#  tag: mytag



- name: notify
  image: plugins/slack
  settings:
    room: drone
    webhook: https://hooks.slack.com/services/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





volumes:
- name: docker
  host:
    path: /var/run/docker.sock
