kind: pipeline
name: default

steps:

- name: build-docker
  image: plugins/docker
  settings:
    repo: kapb14/${DRONE_REPO_NAME}
    context: src/src/
    auto_tag: true
    #dockerfile: src/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: build-notify
  image: plugins/slack
  settings:
    room: drone
    webhook: https://hooks.slack.com/services/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

- name: publish
  image: plugins/gcr
  settings:
    repo: kapb14/${DRONE_REPO_NAME}
    tags: latest
    json_key:
      from_secret: google_credentials

- name: publish-notify
  image: plugins/slack
  settings:
    room: drone
    webhook: https://hooks.slack.com/services/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

#- name: deploy
#  image: quay.io/honestbee/drone-kubernetes
#  kubernetes_server: https://kubernetes.company.org
#  kubernetes_token: CXHVLJSDKJFS...
#  namespace: default
#  deployment: digitaloctober-example
#  repo: myorg/myrepo
#  container: my-container
#  tag: mytag

#commands:
#- docker build -t ${DRONE_REPO_NAME}:${DRONE_COMMIT_SHA} ./src



