# eu.gcr.io
# digitaloctober-nuxt
kind: pipeline
name: build
trigger:
  branch:
  - master
  event:
  - push
  - pull_request

steps:
- name: inspect
  image: alpine
  commands:
  - printenv | sort
  - find -name Dockerfile -type f

- name: build-and-push
  # image: plugins/docker
  image: plugins/gcr
  settings:
    dockerfile: src/Dockerfile
    auto_tag: true
    tags: latest
    registry: eu.gcr.io
    repo: digitaloctober-nuxt/${DRONE_REPO_NAME}
    json_key:
      from_secret: registry_credentials
    # repo: eu.gcr.io/digitaloctober-nuxt/${DRONE_REPO_NAME}
    # repo: kapb14/${DRONE_REPO_NAME}
    # username:
    #   from_secret: docker_username
    # password:
    #   from_secret: docker_password

- name: build-notify
  image: plugins/slack
  settings:
    room: drone
    webhook:
      from_secret: slack_webhook_url


---
kind: pipeline
name: deploy
depends_on:
- build
trigger:
  status:
    - success
steps:
- name: deploy
  image: quay.io/honestbee/drone-kubernetes
  kubernetes_server:
    from_secret: kubernetes_server_secret
  kubernetes_token:
    from_secret: kubernetes_token_secret
  namespace: default
  deployment: ${DRONE_REPO_NAME}
  repo: eu.gcr.io/digitaloctober-nuxt/${DRONE_REPO_NAME}
  container: my-container
  # tag: mytag
- name: publish-notify
  image: plugins/slack
  settings:
    room: drone
    webhook:
      from_secret: slack_webhook_url
---
# kind: pipeline
# name: rollback
# depends_on:
# - deploy
# trigger:
#   status:
#     - failed
# steps:
# - name: rollback-deployment

